/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.lavanderia.view;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.lavanderia.controller.TabelPelangganModel;
import project.lavanderia.entity.Pelanggan;
import project.lavanderia.database.LavanderiaDatabase;
/**
 *
 * @author Dean
 */
public class AmbilPesananView extends javax.swing.JPanel {
    private LavanderiaDatabase db;
    private TabelPelangganModel model;
    private Pelanggan pelanggan;
    private DefaultTableModel tabModel;
    /**
     * Creates new form AmbilPesananView
     */
    public AmbilPesananView() {
        initComponents();
        model = new TabelPelangganModel();
        tabelDataPesanan.setModel(model);
        getData();
    }

    public void getData( ){
        try{
            Statement stat = LavanderiaDatabase.getConnection().createStatement();
            String sql  = "Select * from PELANGGAN";
            ResultSet res   = stat.executeQuery(sql);
            while(res.next()){
                pelanggan = new Pelanggan();
                pelanggan.setNoid(res.getInt("NOID"));
                pelanggan.setNama(res.getString("NAMA"));
                pelanggan.setAlamat(res.getString("ALAMAT"));
                pelanggan.setTelp(res.getString("TELP"));
                pelanggan.setJenis(res.getString("JENIS"));
                pelanggan.setBerat(res.getDouble("BERAT"));
                pelanggan.setHarga(res.getDouble("HARGA"));

                model.add(pelanggan);
            }
        } catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }
    
    private void cariData(String key){
        try{
            
            Object[] judul_kolom = {"NOID", "NAMA", "ALAMAT", "TELP", "JENIS", "BERAT", "HARGA"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            tabelDataPesanan.setModel(tabModel);
            
            Statement stat = LavanderiaDatabase.getConnection().createStatement();
            String sql  = "SELECT * from PELANGGAN WHERE NOID LIKE '%"+key+"%' OR NAMA LIKE '%"+key+"%' OR ALAMAT LIKE '%"+key+"%'";
            ResultSet res   = stat.executeQuery(sql);             
            while(res.next()){
                Object[] data={
                    res.getString("NOID"),
                    res.getString("NAMA"),
                    res.getString("ALAMAT"),
                    res.getString("TELP"),
                    res.getString("JENIS"),
                    res.getString("BERAT"),
                    res.getString("HARGA"),
                };
                tabModel.addRow(data);
            }             
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataPesanan = new javax.swing.JTable();

        setBackground(new java.awt.Color(181, 174, 236));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 48)); // NOI18N
        jLabel1.setText("Ambil Pesanan");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        tabelDataPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelDataPesanan.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabelDataPesananComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataPesanan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(406, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        String key = txtCari.getText();
        System.out.println(key);

        if(key!=""){
            cariData(key);
        } else {
            getData();
        }
    }//GEN-LAST:event_txtCariKeyReleased

    private void tabelDataPesananComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabelDataPesananComponentShown

    }//GEN-LAST:event_tabelDataPesananComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDataPesanan;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
