/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.lavanderia.view;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.lavanderia.model.TabelPelangganModel;
import project.lavanderia.entity.Pelanggan;
import project.lavanderia.database.LavanderiaDatabase;
/**
 *
 * @author Dean
 */
public class AmbilPesananView extends javax.swing.JPanel {
    private LavanderiaDatabase db;
    private TabelPelangganModel model;
    private Pelanggan pelanggan;
    private DefaultTableModel tabModel;
    private String key;

    
    /**
     * Creates new form AmbilPesananView
     */
    public AmbilPesananView() {
        initComponents();
        model = new TabelPelangganModel();
        tabelDataPesanan.setModel(model);
        getData();        
    }

    public void getData( ){
        try{
            Statement stat = LavanderiaDatabase.getConnection().createStatement();
            String sql  = "Select * from PELANGGAN";
            ResultSet res   = stat.executeQuery(sql);
            while(res.next()){
                pelanggan = new Pelanggan();
                pelanggan.setNoid(res.getInt("NOID"));
                pelanggan.setTanggal(res.getString("TANGGAL"));
                pelanggan.setNama(res.getString("NAMA"));
                pelanggan.setAlamat(res.getString("ALAMAT"));
                pelanggan.setTelp(res.getString("TELP"));
                pelanggan.setJenis(res.getString("JENIS"));
                pelanggan.setBerat(res.getDouble("BERAT"));
                pelanggan.setHarga(res.getDouble("HARGA"));

                model.add(pelanggan);
            }
        } catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }
    
    private void cariData(String key){
        try {
            Object[] judul_kolom = {"NOID", "NAMA", "TANGGAL", "ALAMAT", "TELP", "JENIS", "BERAT", "HARGA"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            tabelDataPesanan.setModel(tabModel);
            
            Statement stat = LavanderiaDatabase.getConnection().createStatement();
            String sql  = "SELECT * from PELANGGAN WHERE NOID LIKE '%"+key+"%' OR NAMA LIKE '%"+key+"%' OR ALAMAT LIKE '%"+key+"%'";
            ResultSet res   = stat.executeQuery(sql);             
            while(res.next()){
                Object[] data={
                    res.getString("NOID"),
                    res.getString("NAMA"),
                    res.getString("TANGGAL"),
                    res.getString("ALAMAT"),
                    res.getString("TELP"),
                    res.getString("JENIS"),
                    res.getString("BERAT"),
                    res.getString("HARGA"),
                };
                tabModel.addRow(data);
            }             
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataPesanan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(181, 174, 236));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ambil Pesanan");

        txtCari.setBackground(new java.awt.Color(230, 207, 236));
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        tabelDataPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelDataPesanan.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabelDataPesananComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataPesanan);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/lavanderia/view/searchfind.jpg"))); // NOI18N
        jLabel3.setText("Cari Data Pelanggan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        key = txtCari.getText();
        System.out.println(key);

        if(key!=""){
            cariData(key);
        } else {
            getData();
        }
    }//GEN-LAST:event_txtCariKeyReleased

    private void tabelDataPesananComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabelDataPesananComponentShown

    }//GEN-LAST:event_tabelDataPesananComponentShown

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        try{
            int selectedRow = tabelDataPesanan.getSelectedRow();
            Object rowID = model.getValueAt(selectedRow,0);
            String sql  = "INSERT INTO pesanan_ambil (`NOID`,`TANGGAL`,`NAMA`,`ALAMAT`,`TELP`,`JENIS`,`BERAT`,`HARGA`)"
                          + "(SELECT `NOID`,`TANGGAL`,`NAMA`,`ALAMAT`,`TELP`,`JENIS`,`BERAT`,`HARGA` FROM pelanggan WHERE NOID = "+rowID+")";
            
            String delete = "DELETE FROM pelanggan WHERE NOID = "+ rowID +"";
            
            Connection conn = LavanderiaDatabase.getConnection();
            PreparedStatement preparedStmt = conn.prepareStatement(sql);
            PreparedStatement PS2 = conn.prepareStatement(delete);
            preparedStmt.execute();
            PS2.execute();
            JOptionPane.showMessageDialog(null, "Data dengan ID "+ rowID + "sudah di ambil");

            
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_jPanel1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDataPesanan;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

    
}
